### ISSUE TITLE
name not propagated when using forcephotometry.ForcePhotometry.from_coords()

### ISSUE THREAD

**Issue by simeonreusch** [MickaelRigault/ztflc#1]
When using 
`fp = forcephotometry.ForcePhotometry.from_coords(STUFF)`
the name given as argument is not propagated (result is called "unknown" instead).
Fix:
` return cls(ZTFTarget.from_coords(ra, dec, jdmin=jdmin, jdmax=jdmax, name=name))`
in forcephotometry.py line 40.

**Comment by MickaelRigault** [comment]
Thanks. Done
